let resul,var1=true,var2;
resul=var1 && var2;
console.log(resul);
var2=false;
resul=var1 && var2;
console.log(resul);
var2=true;
resul=var1 && var2;
console.log(resul);
resul=var1 || var2;
console.log(resul);
var1=false;
resul=var1 || var2;
console.log(resul);
var2=false;
resul=var1 || var2;
console.log(resul);
var1 = !var1;
console.log(resul);
resul =!(var1||var2);
console.log(resul);