let resul, num1=4,num2=0,cad='4';
resul = num1 > num2;
console.log(resul);
resul = num1 < num2;
console.log(resul);
resul = num1 >= num2;
console.log(resul);
resul = num1 <= num2;
console.log(resul);
resul = num1 == num2;
console.log(resul);
resul = num1 != num2;
console.log(resul);
resul = num1 === num2;
console.log(resul);
resul = num1 !== num2;
console.log(resul);